CREATE TABLE blocks (
    base_fee_per_gas TEXT NOT NULL, 
    block_hash TEXT NOT NULL, 
    chain TEXT NOT NULL, 
    difficulty TEXT NOT NULL, 
    extra_data TEXT NOT NULL, 
    gas_limit TEXT NOT NULL, 
    gas_used TEXT NOT NULL, 
    logs_bloom TEXT NOT NULL, 
    miner TEXT NOT NULL, 
    mix_hash TEXT NOT NULL, 
    nonce TEXT NOT NULL, 
    number BIGINT NOT NULL, 
    parent_hash TEXT NOT NULL, 
    receipts_root TEXT NOT NULL, 
    sha3_uncles TEXT NOT NULL, 
    size BIGINT NOT NULL, 
    state_root TEXT NOT NULL, 
    timestamp TEXT NOT NULL, 
    total_difficulty TEXT NOT NULL, 
    transactions BIGINT NOT NULL, 
    -- uncles TEXT[] NOT NULL, 
    PRIMARY KEY (block_hash)
);
